import { ApolloWrapper } from "@/ApolloWrapper";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import BG from "../assets/bg.png";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ApolloWrapper>
          <main
            className="flex min-h-screen flex-col items-center"
            style={{
              background: `url(${BG.src}) no-repeat center center/cover`,
            }}
          >
            <Header />
            {children}
            <Footer />
          </main>
        </ApolloWrapper>
      </body>
    </html>
  );
}
